Fix errorprone CompileTimeConstant error
Fixes:
packages/modules/Wifi/service/java/com/android/server/wifi/WifiVendorHal.java:657: error: [CompileTimeConstant] Non-compile-time constant expression passed to parameter with @CompileTimeConstant type annotation.

Bug: 180604628
Test: m RUN_ERROR_PRONE=1 javac-check
Change-Id: Ib80d96c07de3a735af1a4fa49ff9622077ea591e
Merged-In: Ib80d96c07de3a735af1a4fa49ff9622077ea591e
(cherry picked from commit 321120b63e66a91981f6f21692fbe2b520321cf9)